import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("api/auth/*", "routes/api-auth.ts"),
  route("login", "routes/login.tsx"),
  route("register", "routes/register.tsx"),
  route("verify-email", "routes/verify-email.tsx"),
  route("forgot-password", "routes/forgot-password.tsx"),
  route("reset-password", "routes/reset-password.tsx"),
  route("app", "routes/app-dashboard.tsx"),
  route("app/profile", "routes/app-profile.tsx"),
  route("app/security", "routes/app-security.tsx"),
  route("app/families", "routes/app-families.tsx"),
  route("app/families/new", "routes/app-families-new.tsx"),
  route("app/:familyId", "routes/app-family-dashboard.tsx"),
  route("app/:familyId/members", "routes/app-family-members.tsx"),
  route("app/:familyId/invitations", "routes/app-family-invitations.tsx"),
  route("app/:familyId/children", "routes/app-family-children.tsx"),
  route("app/:familyId/children/new", "routes/app-family-children-new.tsx"),
  route("app/:familyId/children/:childId", "routes/app-family-child-detail.tsx"),
  route("app/:familyId/children/:childId/edit", "routes/app-family-child-edit.tsx"),
  route("app/:familyId/children/:childId/wallet", "routes/app-family-child-wallet.tsx"),
  route("app/:familyId/children/:childId/allowance", "routes/app-family-child-allowance.tsx"),
  route("app/:familyId/withdrawals/new", "routes/app-family-withdrawal-new.tsx"),
  route("app/:familyId/adjustments/new", "routes/app-family-adjustment-new.tsx"),
  route("kids", "routes/kids-index.tsx"),
  route("kids/unlock/:profileRef", "routes/kids-unlock.tsx"),
  route("kids/home", "routes/kids-home.tsx"),
  route("kids/wallet", "routes/kids-wallet.tsx"),
  route("kids/history", "routes/kids-history.tsx"),
  route("invite/:token", "routes/invite.tsx"),
  route("privacy", "routes/privacy.tsx"),
  route("terms", "routes/terms.tsx"),
] satisfies RouteConfig;
